### ISSUE TITLE
Level buddy integration / compatibility?

### ISSUE THREAD

**Issue by poVoq** [Moguri/BlenderPanda#28]
First of all, really cool project!

It would be cool if this could integrate or at least ensure compatibility with the Level Buddy Blender addon, see:
https://matt-lucas.itch.io/level-buddy
or for a modified version:
https://github.com/jpcy/bfg_forge

**Comment by Moguri** [comment]
@poVoq Are you running into any issues with using either of these addons alongside BlenderPanda? BlenderPanda should be able to play nicely with them (assuming blendergltf can export the scenes). What kind of integration are you interested in?

**Comment by poVoq** [comment]
I honestly have not tried it. I am just thinking it would be nice to have a smooth export experience and have Panda3D compatible entity pre-sets for stuff like spawn-points etc that are commonly used in games.

**Comment by Moguri** [comment]
These report is rather broad and not easily actionable, so I'm going to close it. If you run into specific issues with using level buddy with BlenderPanda, or have specific feature requests, please open new issues.
