### ISSUE TITLE
Hiding object in rendered viewport mode does not work

### ISSUE THREAD

**Issue by rdb** [Moguri/BlenderPanda#33]
While in rendered viewport mode, neither "Restrict viewport visibility" (`obj.hide`) nor "Restrict rendering" (`obj.hide_render`) has any impact on the visibility of the object.  It does work when setting this before entering Rendered Viewport mode.

Hiding objects while inspecting scenes (eg. hiding an obstacle to inspect what's behind it) seems like a common enough use case to merit supporting this.

**Comment by Moguri** [comment]
Blender is not flagging the object as updated when visibility changes. BRTE will need to work around this by tracking object visibility itself. On a similar note, blender does not flag a scene as updated if objects are added or removed.

**Comment by Moguri** [comment]
This is now fixed with the new rendered viewport code from 41d527e57cf61a172c1d91c9fc4b2d19aed8d73e
