### ISSUE TITLE
Build Project Error unless plugin enabled globally

### ISSUE THREAD

**Issue by sdfgeoff** [Moguri/BlenderPanda#5]
Upon attempting to build a simple project, the following error is encountered:

```
  File "/home/geoffrey/.config/blender/2.77/scripts/addons/BlenderPanda/pman_build.py", line 33, in <module>
    bpy.ops.panda_engine.export_bam(filepath=dst, copy_images=False, skip_up_to_date=True)
  File "/usr/share/blender/2.77/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.panda_engine.export_bam" error, could not be found

```

The function "bpy.ops.panda_engine.export_bam" does appear to exist when looking at it through the python console.

This problem appears to be resolved if the plugin is enabled in the startup file. (ie enable the plugin then save the user preferences globally).

**Comment by Moguri** [comment]
Thanks for pointing this out! Can you verify that 2b4641239803f4403848a8dfca1eabd5545f94f8 fixes this issue for you?

**Comment by Moguri** [comment]
I am going to assume this issue is fixed for you as well and close this issue. If not, this issue can be re-opened.
